---
- name: omero-zarr-pixel-buffer | Install jar
  become: true
  get_url:
    url: "{{ glencoe_artifactory_baseurl }}/{{ item.group }}/{{ item.name }}/{{ item.version }}/{{ item.name }}-{{ item.version }}.jar"
    dest: "{{ omero_zarr_pixel_buffer_folder }}/{{ item.name }}.jar"
    force: true
  with_items: "{{ zarrpixelbuffer_jar }}"

- name: omero-zarr-pixel-buffer |Install dependency jars
  become: true
  get_url:
    url: "{{ maven_artifactory_url }}/{{ item.group }}/{{ item.name }}/{{ item.version }}/{{ item.name }}-{{ item.version }}.jar"
    dest: "{{ omero_zarr_pixel_buffer_folder }}/{{ item.name }}.jar"
    force: true
  with_items: "{{ zarrpixelbuffer_dep_jars }}"

- name: omero-zarr-pixel-buffer | chown to omero-zarr-pixel-buffer-user
  become: true
  ansible.builtin.file:
    path: "{{ omero_zarr_pixel_buffer_folder }}"
    owner: "{{ omero_zarr_pixel_buffer_user }}"
    group: "{{ omero_zarr_pixel_buffer_user }}"
    state: directory
    recurse: true
