---
- name: omero-zarr-pixel-buffer | Install jar
  become: true
  get_url:
    url: "{{ glencoe_artifactory_baseurl }}/{{ zarrpixelbuffer_jar.group }}/{{ zarrpixelbuffer_jar.name }}/{{ zarrpixelbuffer_jar.version }}/{{ zarrpixelbuffer_jar.name }}-{{ zarrpixelbuffer_jar.version }}.jar"
    dest: "{{ omero_zarr_pixel_buffer_folder }}/{{ zarrpixelbuffer_jar.name }}.jar"
    force: true

- name: omero-zarr-pixel-buffer |Install dependency jars
  become: true
  get_url:
    url: "{{ maven_artifactory_url }}/{{ item.group }}/{{ item.name }}/{{ item.version }}/{{ item.name }}-{{ item.version }}.jar"
    dest: "{{ omero_zarr_pixel_buffer_folder }}/{{ item.name }}.jar"
    force: true
  with_items: "{{ zarrpixelbuffer_dep_jars }}"
